### PR TITLE
feat: added Post

### PR DESCRIPTION
**Pull request by Chakravarthi0**
User can
- add
- edit
- delete
- like  
- bookmark and
- share a post.

### CODE REVIEW

**Review by pritam-kr — APPROVED** [review]
Everything is good saran  🔥

- Good folder structure
- Naming conventions
- clean code
- all features are working nicely

Suggestions: Remove console .log  from catch error handling

**Review by manojasarsa — APPROVED** [review]
The add, edit, delete, like, bookmark, and post sharing is working as expected.
The code seems pretty structured and clean.
Also, the UI is clean.
Good work, Saran!

**Review by msdeshmukh009 — APPROVED** [review]
All the mentioned functionalities are working as expected. But there is a minor bug if the user closes the edit post modal without updating, then if the user tries to create a new post the text is still there.

**Comment by Chakravarthi0** [comment]
> All the mentioned functionalities are working as expected. But there is a minor bug if the user closes the edit post modal without updating, then if the user tries to create a new post the text is still there.

Thanks for review, I will look into it.

**Pull request merged**
